parseGTFS ../../Datasets/Germany/GTFS/ ../../Datasets/Germany/gtfs.binary
gtfsToIntermediate ../../Datasets/Germany/gtfs.binary 20220315 20220316 true false ../../Datasets/Germany/intermediate.binary
reduceGraph ../../Datasets/Germany/intermediate.binary ../../Datasets/Germany/intermediate.binary
reduceToMaximumConnectedComponent ../../Datasets/Germany/intermediate.binary ../../Datasets/Germany/intermediate.binary
reduceGraph ../../Datasets/Germany/intermediate.binary ../../Datasets/Germany/intermediate.binary
makeOneHopTransfers ../../Datasets/Germany/intermediate.binary 86400 ../../Datasets/Germany/intermediate.binary true
intermediateToRAPTOR ../../Datasets/Germany/intermediate.binary ../../Datasets/Germany/raptor.binary
