parseGTFS ../../Datasets/Europe/gtfs/ ../../Datasets/Europe/gtfs.binary
gtfsToIntermediate ../../Datasets/Europe/gtfs.binary 20240625 20240626 true true ../../Datasets/Europe/intermediate.binary
reduceGraph ../../Datasets/Europe/intermediate.binary ../../Datasets/Europe/intermediate.binary
reduceToMaximumConnectedComponent ../../Datasets/Europe/intermediate.binary ../../Datasets/Europe/intermediate.binary
reduceGraph ../../Datasets/Europe/intermediate.binary ../../Datasets/Europe/intermediate.binary
makeOneHopTransfers ../../Datasets/Europe/intermediate.binary 86400 ../../Datasets/Europe/intermediate.binary true
intermediateToRAPTOR ../../Datasets/Europe/intermediate.binary ../../Datasets/Europe/raptor.binary
