parseGTFS ../../Datasets/GTFS/Belgien/ ../../Datasets/Belgien/gtfs.binary
gtfsToIntermediate ../../Datasets/Belgien/gtfs.binary 20220310 20220311 true false ../../Datasets/Belgien/intermediate.binary
reduceGraph ../../Datasets/Belgien/intermediate.binary ../../Datasets/Belgien/intermediate.binary
reduceToMaximumConnectedComponent ../../Datasets/Belgien/intermediate.binary ../../Datasets/Belgien/intermediate.binary
makeIntermediateTransitive ../../Datasets/Belgien/intermediate.binary ../../Datasets/Belgien/intermediate.binary
reduceGraph ../../Datasets/Belgien/intermediate.binary ../../Datasets/Belgien/intermediate.binary
makeOneHopTransfers ../../Datasets/Belgien/intermediate.binary 86400 ../../Datasets/Belgien/intermediate.binary true
intermediateToRAPTOR ../../Datasets/Belgien/intermediate.binary ../../Datasets/Belgien/raptor.binary
createLayoutGraph ../../Datasets/Belgien/raptor.binary ../../Datasets/Belgien/raptor.layout.graph true
